### PR TITLE
Programming, Ruby, Family and Myself

### PR DESCRIPTION
**Pull request by kaznum**
Hi Organizers!
I'm very looking forward to attending Sapporo RubyKaigi 2012 because you are preparing a lot of enjoyable sessions at that place. I cannot say thank you enough :)

If I have a chance, I would like to talk at the lightning talk session.

See you at the Great Kaigi.

My talk abstraction is ...

Why are you programming? For what? Programmers have their own reasons to make softwares. I believe that Programming should not be only for work, money and hobby. I would like to talk frankly about producing my own software by myself and my experience of programming which made our life happier directly throught development of an account book web application with Ruby on Rails.

### CODE REVIEW

**Comment by snoozer05** [comment]
:+1:

**Comment by tricknotes** [comment]
:+1:

**Comment by irasally** [comment]
:+1:

**Comment by kei-s** [comment]
:+1:

**Comment by june29** [comment]
:+1:

**Comment by mrkn** [comment]
:feelsgood:

**Comment by koiwa** [comment]
:+1:

**Comment by imaz** [comment]
:sob::sparkles:

**Comment by sandinist** [comment]
:chain:

**Comment by noplans** [comment]
:+1:

**Comment by snoozer05** [comment]
Congratulations! We’re pleased to tell you that your LT proposal was accepted.

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 LT発表に採択されたことをお知らせします。おめでとうございます。

### 諸注意
- LT開始前に余裕をもって接続確認をしておくようお願いします。
- タイムテーブルに情報が公開されましたら内容をご確認いただき、もし間違いや変更などがございましたら Pull Request にてお知らせ下さい。

**Pull request merged**
